language: ruby
rvm:
  - ree
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
branches:
  only:
    - master
before_install: ./scripts/install-lxc.sh
script: ./scripts/test.sh
notifications:
  email:
    recipients:
      - testlab-ci@lookout.com
    on_success: always
    on_failure: always
  irc:
    channels:
      - "irc.freenode.net#jovelabs"
    use_notice: true
    skip_join: true
