language: ruby

rvm:
  - ree
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0

before_install: sudo ./spec/support/install-lxc.sh

notifications:
  email:
    recipients:
      - testlab-ci@lookout.com
    on_success: always
    on_failure: always
  irc:
    - "irc.freenode.net#jovelabs"
